fos_rest:
    view:
        view_response_listener: true
    body_listener:
        enabled: true
    format_listener:
        rules:
          - { path: ^/api, prefer_extension: true, fallback_format: json }
          - { path: ^/, priorities: [ html ] , fallback_format: html }
